version: '3.8'

services:
  config-server:
    build:
      context: ./Config-server
    container_name: config-server
    hostname: config-server
    ports:
      - "8888:8888"
    networks:
      my-network:
        ipv4_address: 172.19.0.2
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      my-network:
        ipv4_address: 172.19.0.3
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  produit:
    build:
      context: ./Produit
    container_name: produit
    hostname: produit
    ports:
      - "8082:8082"
    networks:
      my-network:
        ipv4_address: 172.19.0.4
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  microservice-commande:
    build:
      context: ./Microservice-commande
    container_name: microservice-commande
    hostname: microservice-commande
    ports:
      - "8081:8081"
    networks:
      my-network:
        ipv4_address: 172.19.0.5
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    hostname: gateway
    ports:
      - "8080:8080"
    networks:
      my-network:
        ipv4_address: 172.19.0.6
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
